/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {
	Id             string       `json:"id,omitempty"`
	Fname          string       `json:"fname,omitempty"`
	Lname          string       `json:"lname,omitempty"`
	Email          string       `json:"email,omitempty"`
	Username       string       `json:"username,omitempty"`
	Password       string       `json:"password,omitempty"`
	Mobile         string       `json:"mobile,omitempty"`
	CreatedAt      string       `json:"createdAt,omitempty"`
	UpdatedAt      string       `json:"updatedAt,omitempty"`
	OrganizationId string       `json:"OrganizationId,omitempty"`
	UserLogs       []UserLog    `json:"UserLogs,omitempty"`
	Devices        []UserDevice `json:"Devices,omitempty"`
}
