/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserLog struct {
	Id string `json:"id,omitempty"`
	Event string `json:"event,omitempty"`
	Description string `json:"description,omitempty"`
	Logtime string `json:"logtime,omitempty"`
	UserId string `json:"UserId,omitempty"`
}
