/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddUserFile struct {
	Ame string `json:"ame"`
	Tate string `json:"tate"`
	Ize float32 `json:"ize"`
	D5 string `json:"d5"`
	LobUri string `json:"lobUri"`
	EssionId float32 `json:"essionId"`
	BlobProviderId float32 `json:"BlobProviderId"`
}
