/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserFile struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	State string `json:"state,omitempty"`
	Size string `json:"size,omitempty"`
	Md5 string `json:"md5,omitempty"`
	BlobUri string `json:"blobUri,omitempty"`
	SessionId string `json:"SessionId,omitempty"`
	BlobProviderId string `json:"BlobProviderId,omitempty"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	UploadStartTime string `json:"uploadStartTime,omitempty"`
	UploadCompleteTime interface{} `json:"uploadCompleteTime,omitempty"`
	BytesUploaded interface{} `json:"bytesUploaded,omitempty"`
	DownloadUri interface{} `json:"downloadUri,omitempty"`
	DownloadExpiry interface{} `json:"downloadExpiry,omitempty"`
}
