/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InlineResponse200 struct {
	User *User `json:"user,omitempty"`
	Token string `json:"token,omitempty"`
	Error_ bool `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
}
