/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SignalProvider struct {
	Id string `json:"id,omitempty"`
	Identifier string `json:"identifier,omitempty"`
	Url string `json:"url,omitempty"`
	PublicKey string `json:"publicKey,omitempty"`
	LastCheckedIn string `json:"lastCheckedIn,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
}
