/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BlobProvider struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name"`
	Url string `json:"url"`
	Type_ string `json:"type"`
	AccessKey string `json:"accessKey"`
	SecretKey string `json:"secretKey"`
	UpdatedAt string `json:"updatedAt,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
}
