/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UpdateFile struct {
	BytesUploaded float32 `json:"bytesUploaded,omitempty"`
	DownloadUri string `json:"downloadUri,omitempty"`
	DownloadExpiry float32 `json:"downloadExpiry,omitempty"`
}
