/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserDevice struct {
	Id string `json:"id,omitempty"`
	Type_ string `json:"type,omitempty"`
	Softwareversion string `json:"softwareversion,omitempty"`
	CreatedAt string `json:"createdAt,omitempty"`
	UserId string `json:"UserId,omitempty"`
	Session *Session `json:"Session,omitempty"`
}
