/*
 *  Remote Desktop Services
 *
 * Documentation automatically generated by the <b>swagger-autogen</b> module.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AddLog struct {
	Event string `json:"event"`
	Description string `json:"description"`
}
